USE P32022;



SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN;
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:07';
SELECT * FROM Clienti;
COMMIT TRAN;

/* non - repeatable reads - evitare */
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:10';
SELECT * FROM Clienti;
COMMIT TRAN;



